# Generated by Django 5.2 on 2025-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
