# Generated by Django 5.2 on 2025-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='allows_family_caregivers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='evv_implementation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='family_caregiver_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='free_training_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='free_training_programs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='future_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='future_requirements_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='has_agency_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='has_consumer_directed_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='has_self_directed_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='registry_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='state',
            name='registry_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='state',
            name='registry_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='state',
            name='registry_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='requires_evv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='salary_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='salary_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='special_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='state',
            name='unique_features',
            field=models.TextField(blank=True),
        ),
    ]
