# Generated by Django 5.2 on 2025-05-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_state_allows_family_caregivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewaiverprogram',
            name='allows_family_caregivers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='family_caregiver_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='free_training_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='free_training_programs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='has_agency_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='has_consumer_directed_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='has_self_directed_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='salary_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='salary_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='special_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statewaiverprogram',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
