# Generated by Django 5.2 on 2025-05-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_certification_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_medicaid_certified', models.BooleanField(default=False)),
                ('is_hospice_certified', models.BooleanField(default=False)),
                ('is_private_duty', models.BooleanField(default=False)),
                ('required_training_hours', models.IntegerField(default=0)),
                ('renewal_cycle_months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('training_hours_required', models.IntegerField(default=0)),
                ('renewal_cycle_months', models.IntegerField(default=12)),
                ('requires_background_check', models.BooleanField(default=True)),
                ('requires_fingerprinting', models.BooleanField(default=False)),
                ('requires_medicaid_cert', models.BooleanField(default=False)),
                ('requires_surety_bond', models.BooleanField(default=False)),
                ('min_bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='caregiver',
            name='is_hospice_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='is_medicaid_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='is_private_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='background_check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='fingerprinting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='medicaid_cert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='surety_bond_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='surety_bond_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='training_hours_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('expired', 'Verification Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='cert_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caregivers.certificationtype'),
        ),
        migrations.CreateModel(
            name='CaregiverStateLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('expired', 'Verification Expired')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.caregiver')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.state')),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='states_licensed',
            field=models.ManyToManyField(blank=True, through='caregivers.CaregiverStateLicense', to='caregivers.state'),
        ),
        migrations.AddField(
            model_name='certification',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caregivers.state'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['status', 'verification_status'], name='caregivers__status_07414b_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['expiry_date'], name='caregivers__expiry__487d2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caregiverstatelicense',
            unique_together={('caregiver', 'state')},
        ),
    ]
