# Generated by Django 5.2 on 2025-05-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_initial_data'),
        ('caregivers', '0003_certificationtype_state_alter_certification_options_and_more'),
    ]

    operations = [
    ]
