# Generated by Django 5.2 on 2025-05-08 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AddField(
            model_name='certification',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(default='Unknown Organization', max_length=200),
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(default='Unnamed Certification', max_length=200),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certification',
            name='number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_experiences', to='caregivers.caregiver'),
        ),
        migrations.CreateModel(
            name='CaregiverExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='caregivers.caregiver')),
                ('certifications', models.ManyToManyField(blank=True, related_name='experiences', to='caregivers.certification')),
                ('skills', models.ManyToManyField(blank=True, to='caregivers.skill')),
            ],
            options={
                'verbose_name': 'Caregiver Experience',
                'verbose_name_plural': 'Caregiver Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
