# Generated by Django 5.2 on 2025-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_merge_20250507_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='pending', max_length=20),
        ),
    ]
