from django.core.management.base import BaseCommand
from caregivers.models import State, StateWaiverProgram

class Command(BaseCommand):
    help = 'Populates Massachusetts waiver programs'

    def handle(self, *args, **kwargs):
        massachusetts = State.objects.get(abbreviation='MA')
        
        waiver_programs = [
            {
                'state': massachusetts,
                'program_name': 'MassHealth Home Health Services',
                'administering_agency': 'Massachusetts Board of Registration in Nursing',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment, skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for MassHealth Home Health, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': False,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': False,
                'has_self_directed_option': False,
                'has_agency_option': True,
                'salary_range_min': 15.00,
                'salary_range_max': 20.00,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/nurse-aide-registry-program',
                'phone': '(617) 973-0900',
                'email': 'masshealth@mass.gov'
            },
            {
                'state': massachusetts,
                'program_name': 'Home Care Program',
                'administering_agency': 'Massachusetts Executive Office of Elder Affairs',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment',
                'unique_requirements': 'Must be 60+ years old, have a disability, or have early-onset Alzheimer\'s/dementia',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Home Care Program, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.50,
                'salary_range_max': 20.50,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/info-details/home-care-program',
                'phone': '(617) 727-7750',
                'email': 'elder.affairs@mass.gov'
            },
            {
                'state': massachusetts,
                'program_name': 'Frail Elder Waiver (FEW)',
                'administering_agency': 'Massachusetts Executive Office of Elder Affairs',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment',
                'unique_requirements': 'Must be 65+ years old, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for FEW, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.00,
                'salary_range_max': 21.00,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/info-details/home-care-program',
                'phone': '(617) 727-7750',
                'email': 'elder.affairs@mass.gov'
            },
            {
                'state': massachusetts,
                'program_name': 'Acquired Brain Injury (ABI) Waivers',
                'administering_agency': 'Massachusetts Executive Office of Health and Human Services',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment',
                'unique_requirements': 'Must have acquired brain injury, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for ABI Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.50,
                'salary_range_max': 21.50,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/info-details/home-care-program',
                'phone': '(617) 573-1600',
                'email': 'masshealth@mass.gov'
            },
            {
                'state': massachusetts,
                'program_name': 'Adult Supports Waiver (ASD Waiver)',
                'administering_agency': 'Massachusetts Executive Office of Health and Human Services',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment',
                'unique_requirements': 'Must have autism spectrum disorder, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for ASD Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.00,
                'salary_range_max': 22.00,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/info-details/home-care-program',
                'phone': '(617) 573-1600',
                'email': 'masshealth@mass.gov'
            },
            {
                'state': massachusetts,
                'program_name': 'Moving Forward Plan (MFP) Waivers',
                'administering_agency': 'Massachusetts Executive Office of Health and Human Services',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment',
                'unique_requirements': 'Must be transitioning from nursing home to community, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Massachusetts Board of Registration in Nursing',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for MFP Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must be a CNA, complete 75-120 hours (typically 75: 59 classroom + 16 clinical) of state-approved HHA training, pass HHA competency evaluation, have high school diploma or equivalent, basic English proficiency, physical ability to perform duties, be 18+ years old, and be registered with Board of Registration in Nursing',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.50,
                'salary_range_max': 22.50,
                'free_training_available': True,
                'free_training_programs': 'Massachusetts Training Portal, State-approved HHA training programs',
                'website': 'https://www.mass.gov/info-details/home-care-program',
                'phone': '(617) 573-1600',
                'email': 'masshealth@mass.gov'
            }
        ]

        for waiver_data in waiver_programs:
            StateWaiverProgram.objects.get_or_create(
                state=waiver_data['state'],
                program_name=waiver_data['program_name'],
                defaults=waiver_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated Massachusetts waiver programs')) 