from django.core.management.base import BaseCommand
from caregivers.models import State

class Command(BaseCommand):
    help = 'Populates the database with all 50 states and their requirements'

    def handle(self, *args, **kwargs):
        states_data = [
            {
                'name': 'Alabama',
                'code': 'AL',
                'training_hours_required': 40,
                'renewal_cycle_months': 12,
                'requires_background_check': True,
                'requires_fingerprinting': True,
                'requires_medicaid_cert': True,
                'requires_surety_bond': True,
                'min_bond_amount': 10000,
                'background_check_validity_months': 12,
                'fingerprinting_validity_months': 12,
                'medicaid_cert_validity_months': 12,
                'surety_bond_validity_months': 12,
                'requires_continuing_education': True,
                'continuing_education_hours_required': 12,
                'continuing_education_cycle_months': 12,
                'requires_cpr_certification': True,
                'cpr_cert_validity_months': 12,
                'requires_first_aid_certification': True,
                'first_aid_cert_validity_months': 12,
                'requires_tb_test': True,
                'tb_test_validity_months': 12,
                'requires_flu_shot': True,
                'requires_covid_vaccination': True,
                'requires_drug_test': True,
                'drug_test_validity_months': 12,
                'requires_physical_exam': True,
                'physical_exam_validity_months': 12,
                'requires_auto_insurance': True,
                'min_auto_insurance_coverage': 100000,
                'requires_liability_insurance': True,
                'min_liability_insurance_coverage': 1000000,
                'requires_workers_comp_insurance': True,
                'requires_health_insurance': True,
                'requires_disability_insurance': True,
                'requires_life_insurance': True,
                'min_life_insurance_coverage': 50000,
                'requires_emergency_contact': True,
                'requires_emergency_backup': True,
                'requires_availability_schedule': True,
                'requires_service_area_definition': True,
                'requires_vehicle_registration': True,
                'requires_drivers_license': True,
                'requires_vehicle_inspection': True,
                'vehicle_inspection_validity_months': 12,
                'requires_vehicle_maintenance_log': True,
                'requires_incident_reporting': True,
                'requires_medication_administration_training': True,
                'requires_infection_control_training': True,
                'requires_emergency_procedures_training': True,
                'requires_cultural_competency_training': True,
                'requires_abuse_prevention_training': True,
                'requires_confidentiality_training': True,
                'requires_hipaa_training': True,
                'hipaa_training_validity_months': 12,
                'requires_osha_training': True,
                'osha_training_validity_months': 12,
                'requires_bloodborne_pathogens_training': True,
                'bloodborne_pathogens_training_validity_months': 12,
                'requires_fire_safety_training': True,
                'fire_safety_training_validity_months': 12,
                'requires_emergency_evacuation_training': True,
                'emergency_evacuation_training_validity_months': 12,
                'requires_disaster_preparedness_training': True,
                'disaster_preparedness_training_validity_months': 12,
                'requires_emergency_communication_training': True,
                'emergency_communication_training_validity_months': 12,
                'requires_emergency_equipment_training': True,
                'emergency_equipment_training_validity_months': 12,
                'requires_emergency_medication_training': True,
                'emergency_medication_training_validity_months': 12,
                'requires_emergency_transportation_training': True,
                'emergency_transportation_training_validity_months': 12,
                'requires_emergency_documentation_training': True,
                'emergency_documentation_training_validity_months': 12,
                'requires_emergency_follow_up_training': True,
                'emergency_follow_up_training_validity_months': 12,
                'requires_emergency_debriefing_training': True,
                'emergency_debriefing_training_validity_months': 12,
                'requires_emergency_quality_improvement_training': True,
                'emergency_quality_improvement_training_validity_months': 12,
                'requires_emergency_risk_management_training': True,
                'emergency_risk_management_training_validity_months': 12,
                'requires_emergency_legal_compliance_training': True,
                'emergency_legal_compliance_training_validity_months': 12,
                'requires_emergency_ethics_training': True,
                'emergency_ethics_training_validity_months': 12,
                'requires_emergency_cultural_competency_training': True,
                'emergency_cultural_competency_training_validity_months': 12,
                'notes': 'Alabama Department of Public Health - Home Health Agency Licensure',
            },
            # Add more states here with their specific requirements
            {
                'name': 'Alaska',
                'code': 'AK',
                'training_hours_required': 40,
                'renewal_cycle_months': 12,
                'requires_background_check': True,
                'requires_fingerprinting': True,
                'requires_medicaid_cert': True,
                'requires_surety_bond': True,
                'min_bond_amount': 10000,
                'background_check_validity_months': 12,
                'fingerprinting_validity_months': 12,
                'medicaid_cert_validity_months': 12,
                'surety_bond_validity_months': 12,
                'requires_continuing_education': True,
                'continuing_education_hours_required': 12,
                'continuing_education_cycle_months': 12,
                'requires_cpr_certification': True,
                'cpr_cert_validity_months': 12,
                'requires_first_aid_certification': True,
                'first_aid_cert_validity_months': 12,
                'requires_tb_test': True,
                'tb_test_validity_months': 12,
                'requires_flu_shot': True,
                'requires_covid_vaccination': True,
                'requires_drug_test': True,
                'drug_test_validity_months': 12,
                'requires_physical_exam': True,
                'physical_exam_validity_months': 12,
                'requires_auto_insurance': True,
                'min_auto_insurance_coverage': 100000,
                'requires_liability_insurance': True,
                'min_liability_insurance_coverage': 1000000,
                'requires_workers_comp_insurance': True,
                'requires_health_insurance': True,
                'requires_disability_insurance': True,
                'requires_life_insurance': True,
                'min_life_insurance_coverage': 50000,
                'requires_emergency_contact': True,
                'requires_emergency_backup': True,
                'requires_availability_schedule': True,
                'requires_service_area_definition': True,
                'requires_vehicle_registration': True,
                'requires_drivers_license': True,
                'requires_vehicle_inspection': True,
                'vehicle_inspection_validity_months': 12,
                'requires_vehicle_maintenance_log': True,
                'requires_incident_reporting': True,
                'requires_medication_administration_training': True,
                'requires_infection_control_training': True,
                'requires_emergency_procedures_training': True,
                'requires_cultural_competency_training': True,
                'requires_abuse_prevention_training': True,
                'requires_confidentiality_training': True,
                'requires_hipaa_training': True,
                'hipaa_training_validity_months': 12,
                'requires_osha_training': True,
                'osha_training_validity_months': 12,
                'requires_bloodborne_pathogens_training': True,
                'bloodborne_pathogens_training_validity_months': 12,
                'requires_fire_safety_training': True,
                'fire_safety_training_validity_months': 12,
                'requires_emergency_evacuation_training': True,
                'emergency_evacuation_training_validity_months': 12,
                'requires_disaster_preparedness_training': True,
                'disaster_preparedness_training_validity_months': 12,
                'requires_emergency_communication_training': True,
                'emergency_communication_training_validity_months': 12,
                'requires_emergency_equipment_training': True,
                'emergency_equipment_training_validity_months': 12,
                'requires_emergency_medication_training': True,
                'emergency_medication_training_validity_months': 12,
                'requires_emergency_transportation_training': True,
                'emergency_transportation_training_validity_months': 12,
                'requires_emergency_documentation_training': True,
                'emergency_documentation_training_validity_months': 12,
                'requires_emergency_follow_up_training': True,
                'emergency_follow_up_training_validity_months': 12,
                'requires_emergency_debriefing_training': True,
                'emergency_debriefing_training_validity_months': 12,
                'requires_emergency_quality_improvement_training': True,
                'emergency_quality_improvement_training_validity_months': 12,
                'requires_emergency_risk_management_training': True,
                'emergency_risk_management_training_validity_months': 12,
                'requires_emergency_legal_compliance_training': True,
                'emergency_legal_compliance_training_validity_months': 12,
                'requires_emergency_ethics_training': True,
                'emergency_ethics_training_validity_months': 12,
                'requires_emergency_cultural_competency_training': True,
                'emergency_cultural_competency_training_validity_months': 12,
                'notes': 'Alaska Department of Health and Social Services - Home Health Agency Licensure',
            },
            # Continue with all 50 states...
        ]

        for state_data in states_data:
            state, created = State.objects.update_or_create(
                code=state_data['code'],
                defaults=state_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created state: {state.name}'))
            else:
                self.stdout.write(self.style.SUCCESS(f'Updated state: {state.name}')) 