from django.core.management.base import BaseCommand
from caregivers.models import State, StateWaiverProgram

class Command(BaseCommand):
    help = 'Populates Minnesota waiver programs'

    def handle(self, *args, **kwargs):
        minnesota = State.objects.get(abbreviation='MN')
        
        waiver_programs = [
            {
                'state': minnesota,
                'program_name': 'Minnesota Health Care Programs (MHCP) – Medicaid Home Health Services',
                'administering_agency': 'Minnesota Department of Health (MDH)',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment, skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for MHCP Home Health, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': False,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': False,
                'has_self_directed_option': False,
                'has_agency_option': True,
                'salary_range_min': 15.00,
                'salary_range_max': 20.00,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.health.state.mn.us/facilities/regulation/homecare/index.html',
                'phone': '(651) 201-4101',
                'email': 'health.homecare@state.mn.us'
            },
            {
                'state': minnesota,
                'program_name': 'Elderly Waiver (EW)',
                'administering_agency': 'Minnesota Department of Human Services (DHS)',
                'services_offered': 'Personal care, respite care, homemaker services, skilled nursing',
                'unique_requirements': 'Must be 65+ years old, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for EW, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.50,
                'salary_range_max': 20.50,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.dhs.state.mn.us/dhs16_137980/',
                'phone': '(651) 431-2000',
                'email': 'dhs.waiver@state.mn.us'
            },
            {
                'state': minnesota,
                'program_name': 'Community Access for Disability Inclusion (CADI) Waiver',
                'administering_agency': 'Minnesota Department of Human Services (DHS)',
                'services_offered': 'Personal care, respite care, homemaker services, skilled nursing',
                'unique_requirements': 'Must have disability, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for CADI Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.00,
                'salary_range_max': 21.00,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.dhs.state.mn.us/dhs16_137980/',
                'phone': '(651) 431-2000',
                'email': 'dhs.waiver@state.mn.us'
            },
            {
                'state': minnesota,
                'program_name': 'Brain Injury (BI) Waiver',
                'administering_agency': 'Minnesota Department of Human Services (DHS)',
                'services_offered': 'Personal care, respite care, homemaker services, skilled nursing',
                'unique_requirements': 'Must have brain injury, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for BI Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.50,
                'salary_range_max': 21.50,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.dhs.state.mn.us/dhs16_137980/',
                'phone': '(651) 431-2000',
                'email': 'dhs.waiver@state.mn.us'
            },
            {
                'state': minnesota,
                'program_name': 'Developmental Disabilities (DD) Waiver',
                'administering_agency': 'Minnesota Department of Human Services (DHS)',
                'services_offered': 'Personal care, respite care, homemaker services, skilled nursing',
                'unique_requirements': 'Must have developmental disability, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for DD Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.00,
                'salary_range_max': 22.00,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.dhs.state.mn.us/dhs16_137980/',
                'phone': '(651) 431-2000',
                'email': 'dhs.waiver@state.mn.us'
            },
            {
                'state': minnesota,
                'program_name': 'Alternative Care (AC) Program',
                'administering_agency': 'Minnesota Department of Human Services (DHS)',
                'services_offered': 'Personal care, respite care, homemaker services, skilled nursing',
                'unique_requirements': 'Must be 65+ years old, not eligible for Medicaid, meet nursing home level of care, and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required',
                'effective_date': '2024-01-01',
                'registry_name': 'Minnesota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for AC Program, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training, pass competency evaluation (written and skills), have high school diploma or GED, be at least 18 years old, and be listed on Minnesota Nurse Aide Registry',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.50,
                'salary_range_max': 22.50,
                'free_training_available': True,
                'free_training_programs': 'MDH Training Portal, State-approved HHA training programs',
                'website': 'https://www.dhs.state.mn.us/dhs16_137980/',
                'phone': '(651) 431-2000',
                'email': 'dhs.waiver@state.mn.us'
            }
        ]

        for waiver_data in waiver_programs:
            StateWaiverProgram.objects.get_or_create(
                state=waiver_data['state'],
                program_name=waiver_data['program_name'],
                defaults=waiver_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated Minnesota waiver programs')) 