from django.core.management.base import BaseCommand
from caregivers.models import State, StateWaiverProgram

class Command(BaseCommand):
    help = 'Populates North Dakota waiver programs'

    def handle(self, *args, **kwargs):
        north_dakota = State.objects.get(abbreviation='ND')
        
        waiver_programs = [
            {
                'state': north_dakota,
                'program_name': 'North Dakota Medicaid Home Health Services',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment, skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; must be employed by a licensed and Medicare/Medicaid-certified home health agency; home health agency visits limited to 50 per member per calendar year (not subject to prior approval); extended hour visits must be prior authorized; face-to-face encounter with a provider required within 90 days before or 30 days after start of services',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Medicaid Home Health, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': False,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': False,
                'has_self_directed_option': False,
                'has_agency_option': True,
                'salary_range_min': 15.00,
                'salary_range_max': 20.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/health/regulation-licensure-and-certification/health-facilities-unit/home-health-agencies',
                'phone': '(701) 328-2352',
                'email': 'healthfacilities@nd.gov'
            },
            {
                'state': north_dakota,
                'program_name': 'Home and Community-Based Services (HCBS) Waiver',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, respite, homemaker, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; revised Medicaid 1915(c) waivers effective January 1, 2025 and April 1, 2025',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for HCBS Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.50,
                'salary_range_max': 20.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/healthcare/medicaid/medicaid-waivers',
                'phone': '(701) 328-2352',
                'email': 'medicaid@nd.gov'
            },
            {
                'state': north_dakota,
                'program_name': 'Children\'s Hospice Home and Community-Based Services Waiver',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, respite, homemaker, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; revised Medicaid 1915(c) waivers effective January 1, 2025 and April 1, 2025',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Children\'s Hospice Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.00,
                'salary_range_max': 21.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/healthcare/medicaid/medicaid-waivers',
                'phone': '(701) 328-2352',
                'email': 'medicaid@nd.gov'
            },
            {
                'state': north_dakota,
                'program_name': 'Children with Medically Fragile Needs Home and Community-Based Services Waiver',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, respite, homemaker, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; revised Medicaid 1915(c) waivers effective January 1, 2025 and April 1, 2025',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Medically Fragile Children Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.50,
                'salary_range_max': 21.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/healthcare/medicaid/medicaid-waivers',
                'phone': '(701) 328-2352',
                'email': 'medicaid@nd.gov'
            },
            {
                'state': north_dakota,
                'program_name': 'Autism Spectrum Disorder Birth through Age 17 Waiver',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, respite, homemaker, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; revised Medicaid 1915(c) waivers effective January 1, 2025 and April 1, 2025',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Autism Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.00,
                'salary_range_max': 22.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/healthcare/medicaid/medicaid-waivers',
                'phone': '(701) 328-2352',
                'email': 'medicaid@nd.gov'
            },
            {
                'state': north_dakota,
                'program_name': 'Traditional Individual with Intellectual Disabilities and Developmental Disabilities Waiver',
                'administering_agency': 'North Dakota Department of Health and Human Services (Division of Health Facilities)',
                'services_offered': 'Personal care, respite, homemaker, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; revised Medicaid 1915(c) waivers effective January 1, 2025 and April 1, 2025',
                'annual_training_requirements': '12 hours annual in-service/continuing education (including at least 2 hours abuse/neglect prevention and 1 hour infection control)',
                'effective_date': '2024-01-01',
                'registry_name': 'North Dakota Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for I/DD Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (required), pass criminal background check and drug screening, and complete competency evaluation program (supervised practical training required)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.50,
                'salary_range_max': 22.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.hhs.nd.gov/healthcare/medicaid/medicaid-waivers',
                'phone': '(701) 328-2352',
                'email': 'medicaid@nd.gov'
            }
        ]

        for waiver_data in waiver_programs:
            StateWaiverProgram.objects.get_or_create(
                state=waiver_data['state'],
                program_name=waiver_data['program_name'],
                defaults=waiver_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated North Dakota waiver programs')) 