from django.core.management.base import BaseCommand
from caregivers.models import State, StateWaiverProgram

class Command(BaseCommand):
    help = 'Populates Texas waiver programs'

    def handle(self, *args, **kwargs):
        texas = State.objects.get(abbreviation='TX')
        
        waiver_programs = [
            {
                'state': texas,
                'program_name': 'STAR+PLUS (Medicaid Managed Care for adults with disabilities/elderly)',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for STAR+PLUS, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.00,
                'salary_range_max': 20.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'hcssa@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'STAR Kids (Medicaid Managed Care for children with disabilities)',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for STAR Kids, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.50,
                'salary_range_max': 20.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'starkids@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Home and Community-Based Services (HCS) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for HCS Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.00,
                'salary_range_max': 21.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'hcs@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Texas Home Living (TxHmL) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for TxHmL Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.50,
                'salary_range_max': 21.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'txhml@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Community Living Assistance and Support Services (CLASS) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for CLASS Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.00,
                'salary_range_max': 22.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'class@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Deaf Blind with Multiple Disabilities (DBMD) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for DBMD Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.50,
                'salary_range_max': 22.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'dbmd@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Medically Dependent Children Program (MDCP) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for MDCP Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 18.00,
                'salary_range_max': 23.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'mdcp@hhsc.state.tx.us'
            },
            {
                'state': texas,
                'program_name': 'Youth Empowerment Services (YES) Waiver',
                'administering_agency': 'Texas Health and Human Services Commission (HHSC)',
                'services_offered': 'Personal care, respite, homemaker, skilled nursing, and home modifications',
                'unique_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must be employed by a licensed home health agency for Medicaid/Medicare reimbursement; annual competency testing/evaluation on 13 key subject areas required; alternate paths: 1 year full-time experience in direct client care in institutional/agency setting, or nursing student with documentation of basic skills; special 59-hour online HHA course available for entry-level training (not for Medicare/Medicaid-certified agencies)',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification',
                'effective_date': '2024-01-01',
                'registry_name': 'Texas Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for YES Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program; must pass written and skills competency evaluation; must be at least 18 years old; must pass criminal background check; family members (not spouses) can be paid caregivers',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 18.50,
                'salary_range_max': 23.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available; expanded online and Spanish-language training modules available',
                'website': 'https://www.hhs.texas.gov/providers/long-term-care-providers/home-community-support-services-agencies-hcssa',
                'phone': '(512) 438-3011',
                'email': 'yes@hhsc.state.tx.us'
            }
        ]

        for waiver_data in waiver_programs:
            StateWaiverProgram.objects.get_or_create(
                state=waiver_data['state'],
                program_name=waiver_data['program_name'],
                defaults=waiver_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated Texas waiver programs')) 