from django.core.management.base import BaseCommand
from caregivers.models import State, StateWaiverProgram

class Command(BaseCommand):
    help = 'Populates Ohio waiver programs'

    def handle(self, *args, **kwargs):
        ohio = State.objects.get(abbreviation='OH')
        
        waiver_programs = [
            {
                'state': ohio,
                'program_name': 'Ohio Medicaid Home Health Services',
                'administering_agency': 'Ohio Department of Health (ODH)',
                'services_offered': 'Personal care, homemaker services, respite care, adult day health, home-delivered meals, home modifications, medical supplies and equipment, skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; must be employed by a Medicare-certified home health agency for Medicaid reimbursement; home health aide visits are part-time/intermittent (up to 4 hours per visit, up to 8 hours/day, up to 14 hours/week unless prior authorized); home health services cannot be used for respite care; additional services (beyond limits) require prior authorization or recent hospitalization; all home health agencies and non-agency providers must be licensed by ODH as of July 1, 2022 (O.R.C. § 3740.01); licenses valid for three years, renewable with continued compliance',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Medicaid Home Health, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': False,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': False,
                'has_self_directed_option': False,
                'has_agency_option': True,
                'salary_range_min': 15.00,
                'salary_range_max': 20.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://odh.ohio.gov/know-our-programs/home-health-agencies/home-health-agency-licensure',
                'phone': '(614) 644-8548',
                'email': 'homehealth@odh.ohio.gov'
            },
            {
                'state': ohio,
                'program_name': 'PASSPORT Waiver Program',
                'administering_agency': 'Ohio Department of Aging (ODA)',
                'services_offered': 'Personal care, homemaker, respite, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; for older adults, home and community-based services',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for PASSPORT Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 15.50,
                'salary_range_max': 20.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.help4seniors.org/wp-content/uploads/Downloads/fact-sheets/OHCW2016.pdf',
                'phone': '(614) 644-8548',
                'email': 'passport@aging.ohio.gov'
            },
            {
                'state': ohio,
                'program_name': 'MyCare Ohio',
                'administering_agency': 'Ohio Department of Medicaid (ODM)',
                'services_offered': 'Personal care, homemaker, respite, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI; Medicaid/Medicare managed care for dual-eligibles',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for MyCare Ohio, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.00,
                'salary_range_max': 21.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://www.caresource.com/plans/ohio-waiver-services/',
                'phone': '(614) 644-8548',
                'email': 'mycare@medicaid.ohio.gov'
            },
            {
                'state': ohio,
                'program_name': 'Program for the All-Inclusive Care of the Elderly (PACE)',
                'administering_agency': 'Ohio Department of Medicaid (ODM)',
                'services_offered': 'Personal care, homemaker, respite, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for PACE, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 16.50,
                'salary_range_max': 21.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://medicaid.ohio.gov/resources-for-providers/enrollment-and-support/provider-types/ohcp/',
                'phone': '(614) 644-8548',
                'email': 'pace@medicaid.ohio.gov'
            },
            {
                'state': ohio,
                'program_name': 'Medicaid Managed Care Plans',
                'administering_agency': 'Ohio Department of Medicaid (ODM)',
                'services_offered': 'Personal care, homemaker, respite, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for Managed Care Plan, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.00,
                'salary_range_max': 22.00,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://medicaid.ohio.gov/resources-for-providers/enrollment-and-support/provider-types/ohcp/',
                'phone': '(614) 644-8548',
                'email': 'managedcare@medicaid.ohio.gov'
            },
            {
                'state': ohio,
                'program_name': 'Ohio Department of Aging (ODA) and Ohio Department of Developmental Disabilities (DODD) HCBS Waivers',
                'administering_agency': 'Ohio Department of Aging (ODA) and Ohio Department of Developmental Disabilities (DODD)',
                'services_offered': 'Personal care, homemaker, respite, and skilled nursing',
                'unique_requirements': 'Must meet nursing home level of care and have income below 300% of SSI',
                'annual_training_requirements': '12 hours annual in-service/continuing education required to maintain certification; certificate renewal every two years',
                'effective_date': '2024-01-01',
                'registry_name': 'Ohio Nurse Aide Registry',
                'registry_update_frequency': 'As needed',
                'required_forms': 'Application for HCBS Waiver, Level of Care Assessment, Financial Assessment',
                'allows_family_caregivers': True,
                'family_caregiver_requirements': 'Must complete 75 total hours (16 clinical) of state-approved HHA training program, pass written and skills competency evaluation, have high school diploma or GED (recommended by most employers), be at least 18 years old (recommended by most employers), pass criminal background check (required before employment/certification), and pass fingerprinting (required for agency licensure and some employment)',
                'has_consumer_directed_option': True,
                'has_self_directed_option': True,
                'has_agency_option': True,
                'salary_range_min': 17.50,
                'salary_range_max': 22.50,
                'free_training_available': True,
                'free_training_programs': 'On-the-job training and approved programs available',
                'website': 'https://medicaid.ohio.gov/resources-for-providers/enrollment-and-support/provider-types/ohcp/',
                'phone': '(614) 644-8548',
                'email': 'hcbs@aging.ohio.gov'
            }
        ]

        for waiver_data in waiver_programs:
            StateWaiverProgram.objects.get_or_create(
                state=waiver_data['state'],
                program_name=waiver_data['program_name'],
                defaults=waiver_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully populated Ohio waiver programs')) 